---
- name: publish CloudFormation template
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    bucket: "conjur-ci-public"
  tasks:
    - name: write template to S3
      aws_s3:
        bucket: "{{ bucket }}"
        object: "cloudformation/conjur-latest.yml"
        src: "/ansible/conjur-{{ conjur_version }}.yml"
        mode: put
